name: "skoda-tendr-challenges-and-rewards"

services:
  postgres:
    image: 'postgres:latest'
    restart: unless-stopped
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - "5432:5432"
  backend:
    container_name: backend
    restart: unless-stopped
    build:
      dockerfile: src/main/resources/Dockerfile
      context: ./
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mydatabase
    depends_on:
      - postgres
    ports:
      - "8080:8080"
